import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
// import Header from '../components/Header-exemple'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import {table, minifyRecords} from './api/utils/Airtable';
import Todo from '../components/Todo';


export default function profils(initialTodos) {
  console.log(initialTodos);
  return (
    <div className={styles.container}>
      {/* <Header/> */}

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
        <h3 className={styles.title_h3}>
          <Link href="/">
            <a>Retour à l'accueil</a>
          </Link>
        </h3>

          {initialTodos.initialTodos.map((todo) => (
            <Todo key={todo.id} todo={todo} />
          ))}
          
      </main>
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
    </div>
  )
}


export async function getServerSideProps(context) {
  try{
    const todos = await table.select({}).firstPage();
    return {
      props: {
        initialTodos: minifyRecords(todos)
      }
    }
  }catch(err){
    console.error(err)
    return{
      props: {
        err: "Aucune données trouvées"
      }
    }
  }
}
